#!/bin/bash
#
# Build hook for Docker Automated Build.
#
# This hooks modifies the Dockerfile by inserting the image version in the
# related label.
#

echo "Environment variables:

"

docker build  -f $DOCKERFILE_PATH -t $IMAGE_NAME .
