#!/bin/bash
echo "Environment variables:
  SOURCE_BRANCH=$SOURCE_BRANCH
  SOURCE_COMMIT=$SOURCE_COMMIT
  COMMIT_MSG=$COMMIT_MSG
  DOCKER_REPO=$DOCKER_REPO
  DOCKERFILE_PATH=$DOCKERFILE_PATH
  CACHE_TAG=$CACHE_TAG
  IMAGE_NAME=$IMAGE_NAME
  
  DOCKER_TAG=$DOCKER_TAG
  IMAGE_VERSION=$IMAGE_VERSION
"
docker tag $IMAGE_NAME ${DOCKER_REPO}:test
echo "Pushing image..."
docker push ${DOCKER_REPO}:test

echo "post_push hook terminated successfully."
