#!/bin/bash
echo "=> Test Pre Build"
echo "Environment variables:
  SOURCE_BRANCH=$SOURCE_BRANCH
  SOURCE_COMMIT=$SOURCE_COMMIT
  COMMIT_MSG=$COMMIT_MSG
  DOCKER_REPO=$DOCKER_REPO
  DOCKERFILE_PATH=$DOCKERFILE_PATH
  CACHE_TAG=$CACHE_TAG
  IMAGE_NAME=$IMAGE_NAME
  
  DOCKER_TAG=$DOCKER_TAG
  IMAGE_VERSION=$IMAGE_VERSION
"
echo "curl"
var = curl -s "https://github.com/kovidgoyal/calibre/tags.atom" | grep -oP '(?<=<id>tag:github.com,2008:Repository/10332822/v).*?(?= </id>)'
echo $var
